# -*- coding: utf-8 -*-
"""DecisionTree_ML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JzcKG97Cih7rKfId4J0SS9FNBJfTEag1
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df= pd.read_csv('/content/spambase1.csv')
df.head()

x = df.drop('output',axis=1)
x

y = df.output
y

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y ,test_size=0.3, random_state=0)

from sklearn.preprocessing import StandardScaler
st_x= StandardScaler()
x_train= st_x.fit_transform(x_train)
x_test= st_x.transform(x_test)

from sklearn.tree import DecisionTreeClassifier
classifier= DecisionTreeClassifier(criterion='entropy',random_state=0) 
classifier.fit(x_train, y_train)

y_pred=classifier.predict(x_test)
y_pred

import matplotlib.pyplot as plt
import numpy
from sklearn import metrics

confusion_matrix = metrics.confusion_matrix(y_pred,y_test)
confusion_matrix
plt.plot(confusion_matrix)

from sklearn.tree import export_graphviz
import graphviz
graphviz.Source(export_graphviz(classifier,feature_names=x.columns,filled=False,class_names=['1','2','3','4','5','6','7'],out_file=None))

